/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SoforthilfeRouteImport } from './routes/soforthilfe'
import { Route as NebenklageRouteImport } from './routes/nebenklage'
import { Route as LeistungenRouteImport } from './routes/leistungen'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as KanzleiRouteImport } from './routes/kanzlei'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as DatenschutzRouteImport } from './routes/datenschutz'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EnIndexRouteImport } from './routes/en.index'
import { Route as EnSoforthilfeRouteImport } from './routes/en.soforthilfe'
import { Route as EnNebenklageRouteImport } from './routes/en.nebenklage'
import { Route as EnLeistungenRouteImport } from './routes/en.leistungen'
import { Route as EnKontaktRouteImport } from './routes/en.kontakt'
import { Route as EnKanzleiRouteImport } from './routes/en.kanzlei'
import { Route as EnImpressumRouteImport } from './routes/en.impressum'
import { Route as EnDatenschutzRouteImport } from './routes/en.datenschutz'

const SoforthilfeRoute = SoforthilfeRouteImport.update({
  id: '/soforthilfe',
  path: '/soforthilfe',
  getParentRoute: () => rootRouteImport,
} as any)
const NebenklageRoute = NebenklageRouteImport.update({
  id: '/nebenklage',
  path: '/nebenklage',
  getParentRoute: () => rootRouteImport,
} as any)
const LeistungenRoute = LeistungenRouteImport.update({
  id: '/leistungen',
  path: '/leistungen',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const KanzleiRoute = KanzleiRouteImport.update({
  id: '/kanzlei',
  path: '/kanzlei',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const DatenschutzRoute = DatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnIndexRoute = EnIndexRouteImport.update({
  id: '/en/',
  path: '/en/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnSoforthilfeRoute = EnSoforthilfeRouteImport.update({
  id: '/en/soforthilfe',
  path: '/en/soforthilfe',
  getParentRoute: () => rootRouteImport,
} as any)
const EnNebenklageRoute = EnNebenklageRouteImport.update({
  id: '/en/nebenklage',
  path: '/en/nebenklage',
  getParentRoute: () => rootRouteImport,
} as any)
const EnLeistungenRoute = EnLeistungenRouteImport.update({
  id: '/en/leistungen',
  path: '/en/leistungen',
  getParentRoute: () => rootRouteImport,
} as any)
const EnKontaktRoute = EnKontaktRouteImport.update({
  id: '/en/kontakt',
  path: '/en/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const EnKanzleiRoute = EnKanzleiRouteImport.update({
  id: '/en/kanzlei',
  path: '/en/kanzlei',
  getParentRoute: () => rootRouteImport,
} as any)
const EnImpressumRoute = EnImpressumRouteImport.update({
  id: '/en/impressum',
  path: '/en/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const EnDatenschutzRoute = EnDatenschutzRouteImport.update({
  id: '/en/datenschutz',
  path: '/en/datenschutz',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/kanzlei': typeof KanzleiRoute
  '/kontakt': typeof KontaktRoute
  '/leistungen': typeof LeistungenRoute
  '/nebenklage': typeof NebenklageRoute
  '/soforthilfe': typeof SoforthilfeRoute
  '/en/datenschutz': typeof EnDatenschutzRoute
  '/en/impressum': typeof EnImpressumRoute
  '/en/kanzlei': typeof EnKanzleiRoute
  '/en/kontakt': typeof EnKontaktRoute
  '/en/leistungen': typeof EnLeistungenRoute
  '/en/nebenklage': typeof EnNebenklageRoute
  '/en/soforthilfe': typeof EnSoforthilfeRoute
  '/en/': typeof EnIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/kanzlei': typeof KanzleiRoute
  '/kontakt': typeof KontaktRoute
  '/leistungen': typeof LeistungenRoute
  '/nebenklage': typeof NebenklageRoute
  '/soforthilfe': typeof SoforthilfeRoute
  '/en/datenschutz': typeof EnDatenschutzRoute
  '/en/impressum': typeof EnImpressumRoute
  '/en/kanzlei': typeof EnKanzleiRoute
  '/en/kontakt': typeof EnKontaktRoute
  '/en/leistungen': typeof EnLeistungenRoute
  '/en/nebenklage': typeof EnNebenklageRoute
  '/en/soforthilfe': typeof EnSoforthilfeRoute
  '/en': typeof EnIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/kanzlei': typeof KanzleiRoute
  '/kontakt': typeof KontaktRoute
  '/leistungen': typeof LeistungenRoute
  '/nebenklage': typeof NebenklageRoute
  '/soforthilfe': typeof SoforthilfeRoute
  '/en/datenschutz': typeof EnDatenschutzRoute
  '/en/impressum': typeof EnImpressumRoute
  '/en/kanzlei': typeof EnKanzleiRoute
  '/en/kontakt': typeof EnKontaktRoute
  '/en/leistungen': typeof EnLeistungenRoute
  '/en/nebenklage': typeof EnNebenklageRoute
  '/en/soforthilfe': typeof EnSoforthilfeRoute
  '/en/': typeof EnIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/datenschutz'
    | '/impressum'
    | '/kanzlei'
    | '/kontakt'
    | '/leistungen'
    | '/nebenklage'
    | '/soforthilfe'
    | '/en/datenschutz'
    | '/en/impressum'
    | '/en/kanzlei'
    | '/en/kontakt'
    | '/en/leistungen'
    | '/en/nebenklage'
    | '/en/soforthilfe'
    | '/en/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/datenschutz'
    | '/impressum'
    | '/kanzlei'
    | '/kontakt'
    | '/leistungen'
    | '/nebenklage'
    | '/soforthilfe'
    | '/en/datenschutz'
    | '/en/impressum'
    | '/en/kanzlei'
    | '/en/kontakt'
    | '/en/leistungen'
    | '/en/nebenklage'
    | '/en/soforthilfe'
    | '/en'
  id:
    | '__root__'
    | '/'
    | '/datenschutz'
    | '/impressum'
    | '/kanzlei'
    | '/kontakt'
    | '/leistungen'
    | '/nebenklage'
    | '/soforthilfe'
    | '/en/datenschutz'
    | '/en/impressum'
    | '/en/kanzlei'
    | '/en/kontakt'
    | '/en/leistungen'
    | '/en/nebenklage'
    | '/en/soforthilfe'
    | '/en/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DatenschutzRoute: typeof DatenschutzRoute
  ImpressumRoute: typeof ImpressumRoute
  KanzleiRoute: typeof KanzleiRoute
  KontaktRoute: typeof KontaktRoute
  LeistungenRoute: typeof LeistungenRoute
  NebenklageRoute: typeof NebenklageRoute
  SoforthilfeRoute: typeof SoforthilfeRoute
  EnDatenschutzRoute: typeof EnDatenschutzRoute
  EnImpressumRoute: typeof EnImpressumRoute
  EnKanzleiRoute: typeof EnKanzleiRoute
  EnKontaktRoute: typeof EnKontaktRoute
  EnLeistungenRoute: typeof EnLeistungenRoute
  EnNebenklageRoute: typeof EnNebenklageRoute
  EnSoforthilfeRoute: typeof EnSoforthilfeRoute
  EnIndexRoute: typeof EnIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/soforthilfe': {
      id: '/soforthilfe'
      path: '/soforthilfe'
      fullPath: '/soforthilfe'
      preLoaderRoute: typeof SoforthilfeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nebenklage': {
      id: '/nebenklage'
      path: '/nebenklage'
      fullPath: '/nebenklage'
      preLoaderRoute: typeof NebenklageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leistungen': {
      id: '/leistungen'
      path: '/leistungen'
      fullPath: '/leistungen'
      preLoaderRoute: typeof LeistungenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kanzlei': {
      id: '/kanzlei'
      path: '/kanzlei'
      fullPath: '/kanzlei'
      preLoaderRoute: typeof KanzleiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datenschutz': {
      id: '/datenschutz'
      path: '/datenschutz'
      fullPath: '/datenschutz'
      preLoaderRoute: typeof DatenschutzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/': {
      id: '/en/'
      path: '/en'
      fullPath: '/en/'
      preLoaderRoute: typeof EnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/soforthilfe': {
      id: '/en/soforthilfe'
      path: '/en/soforthilfe'
      fullPath: '/en/soforthilfe'
      preLoaderRoute: typeof EnSoforthilfeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/nebenklage': {
      id: '/en/nebenklage'
      path: '/en/nebenklage'
      fullPath: '/en/nebenklage'
      preLoaderRoute: typeof EnNebenklageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/leistungen': {
      id: '/en/leistungen'
      path: '/en/leistungen'
      fullPath: '/en/leistungen'
      preLoaderRoute: typeof EnLeistungenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/kontakt': {
      id: '/en/kontakt'
      path: '/en/kontakt'
      fullPath: '/en/kontakt'
      preLoaderRoute: typeof EnKontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/kanzlei': {
      id: '/en/kanzlei'
      path: '/en/kanzlei'
      fullPath: '/en/kanzlei'
      preLoaderRoute: typeof EnKanzleiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/impressum': {
      id: '/en/impressum'
      path: '/en/impressum'
      fullPath: '/en/impressum'
      preLoaderRoute: typeof EnImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/datenschutz': {
      id: '/en/datenschutz'
      path: '/en/datenschutz'
      fullPath: '/en/datenschutz'
      preLoaderRoute: typeof EnDatenschutzRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DatenschutzRoute: DatenschutzRoute,
  ImpressumRoute: ImpressumRoute,
  KanzleiRoute: KanzleiRoute,
  KontaktRoute: KontaktRoute,
  LeistungenRoute: LeistungenRoute,
  NebenklageRoute: NebenklageRoute,
  SoforthilfeRoute: SoforthilfeRoute,
  EnDatenschutzRoute: EnDatenschutzRoute,
  EnImpressumRoute: EnImpressumRoute,
  EnKanzleiRoute: EnKanzleiRoute,
  EnKontaktRoute: EnKontaktRoute,
  EnLeistungenRoute: EnLeistungenRoute,
  EnNebenklageRoute: EnNebenklageRoute,
  EnSoforthilfeRoute: EnSoforthilfeRoute,
  EnIndexRoute: EnIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
